### PR TITLE
Math magicians: events

### PR DESCRIPTION
**Pull request by roodjinocherilus**
In this PR I have:
- Created a new directory called logic inside my project
- Copied the files calculate.js and operate.js into my logic/ directory
- Import calculate.js in your Calculator.js component
- Implement click event handlers using the math logic from calculate.js and operate.js in my React component
- Made all calculator buttons work according to their functionality

### CODE REVIEW

**Comment by rloterh** [comment]
@roodjinocherilus 
The key Features section of the ReadMe is not filled. Kindly add 1 -3 features of your app in the ReadMe. Asap pls!

**Comment by rloterh** [comment]
@roodjinocherilus 
Key Features section is still empty
image

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Roodjino,  

Your project is complete! 🏁 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉 💯 🌟 

## Highlights 🎯 
🎲  Properly added math logic files!
🎲  Events handling properly implemented!
🎲  Calculator App is working as intended!
🎲  Professional ReadMe!

## Optional suggestions 🧰 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

**You can also consider:**
- Kindly ensure that the _Getting Started_ section_ is filled with the appropriate instructions on how to _setup_ and _run_ your app, for instance, using commands such as `npm i` or `npm start`.
- Implementing the above change(s) will make your ReadMe/ repository stand out even better! 😉

Cheers..Happy coding! 💻  🍷  🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by mwanawabangona — COMMENTED** [review]
Hi @roodjinocherilus,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  


## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
